In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,20)

In [3]:
a = np.random.randint(1,20, size=20)
b = np.random.randint(1,10, size=10)
print(a, b, sep="\n\n")

[ 5  8 14  9  9 12  3 12  5 19 11  2 11  7 14  6  1 18 13  1]

[3 3 2 7 1 3 4 9 9 8]


In [4]:
[True if x in b else False for x in b]

[True, True, True, True, True, True, True, True, True, True]

In [5]:
np.in1d(b, a)

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True])

# Stacking

In [6]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")

np.stack((a,b), axis=0)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [7]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")

np.stack((a,b), axis=1)

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [8]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")

np.hstack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  3,  6,  9, 12, 15, 18, 21,
       24, 27, 30])

In [9]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")

np.vstack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [10]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 10
print(a,b, sep="\n\n")

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]


In [11]:
np.dstack((a,b))

array([[[ 0,  1, 10, 11],
        [ 2,  3, 12, 13]],

       [[ 4,  5, 14, 15],
        [ 6,  7, 16, 17]]])

In [14]:
a = np.arange(2*2).reshape(2,2)
print(a)
a + 5

[[0 1]
 [2 3]]


array([[5, 6],
       [7, 8]])

In [15]:
b = np.full_like(a, 5)
print(a,b, sep="\n\n")

[[0 1]
 [2 3]]

[[5 5]
 [5 5]]


In [16]:
a + b

array([[5, 6],
       [7, 8]])

In [17]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")
np.column_stack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  3],
       [ 2,  6],
       [ 3,  9],
       [ 4, 12],
       [ 5, 15],
       [ 6, 18],
       [ 7, 21],
       [ 8, 24],
       [ 9, 27],
       [10, 30]])

In [18]:
a = np.arange(1,11)
b = a * 3
print(a, b, sep="\n\n")
np.row_stack((a,b))

[ 1  2  3  4  5  6  7  8  9 10]

[ 3  6  9 12 15 18 21 24 27 30]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30]])

In [31]:
a = np.arange(6*6).reshape((6,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
print(a)
np.split(a,2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [33]:
print(a)
np.split(a,2, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [34]:
a = np.random.randint(1,20, size=20)
b = np.random.randint(1,10, size=10)
print(a, b, sep="\n\n")
np.intersect1d(a,b)

[17  8  4 12 10 14 10 10 10  5  1  7 11 15 16 11  4  8 16 15]

[1 8 4 2 7 5 2 3 7 9]


array([1, 4, 5, 7, 8])

In [35]:
a = np.random.randint(1,20, size=20)
b = np.random.randint(1,10, size=10)
print(a, b, sep="\n\n")
np.union1d(a,b)

[15 12  8 10  2  1  7 10  4  3 12 14 14  3 15  8 13  8 15  3]

[3 9 8 2 8 1 7 8 2 7]


array([ 1,  2,  3,  4,  7,  8,  9, 10, 12, 13, 14, 15])

In [36]:
a = np.random.randint(1,20, size=20)
b = np.random.randint(1,10, size=10)
print(a, b, sep="\n\n")
np.setdiff1d(a,b)

[14  1  5 10 11  2 11 12 15  8  8 13  1 11  6 15 19  3  7  2]

[5 1 5 7 2 5 5 3 7 8]


array([ 6, 10, 11, 12, 13, 14, 15, 19])

In [37]:
np.setxor1d(a, b)
# 0 0 - 0
# 1 0 - 1
# 0 1 - 1
# 1 1 - 0


array([ 6, 10, 11, 12, 13, 14, 15, 19])