In [1]:
import numpy as np

In [3]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#C(B(A(1)))
#A(B(C(1)))
#A().B().C()

In [4]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a.dtype)

int64


In [6]:
a = np.arange(1,13).reshape(3,4).astype('float64')
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [7]:
a = np.arange(1,13).astype(np.float64).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [8]:
a = np.arange(1,13, dtype=np.float32).reshape(3,4)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [10]:
np.random.randn(3,3,3) * 5

array([[[-1.44188126,  2.84653819,  5.51100298],
        [-2.66824474, -5.80192994, -4.06914063],
        [ 7.52920151, -7.94616824, -4.94654699]],

       [[ 0.99156882,  3.39190736,  2.80254529],
        [-1.07498238,  8.68092445,  2.16823967],
        [ 2.17033611,  0.93668049, -7.30323588]],

       [[ 0.30908343,  1.0970347 , -3.08942409],
        [ 8.62476034, -2.02366836,  1.36872494],
        [ 7.84955032, 12.1760018 , -6.87956275]]])

In [13]:
a = np.ones((3,3,3), dtype=np.int64)
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [14]:
a = np.zeros((3,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [17]:
a.shape

(3, 3, 3)

In [18]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [19]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.ones_like(a) * 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
np.ones_like(a) + 4

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [24]:
np.full((3,3,3), 5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [25]:
np.full_like(a, 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [26]:
np.empty((3,3,3))

array([[[4.65312258e-310, 4.65312304e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 6.95178442e-310]],

       [[0.00000000e+000, 0.00000000e+000, 4.65312133e-310],
        [4.65312133e-310, 6.95174646e-310, 6.95178443e-310],
        [4.65312133e-310, 0.00000000e+000, 6.95174681e-310]],

       [[6.95174646e-310, 6.95174609e-310, 4.65312133e-310],
        [6.95178442e-310, 6.95178442e-310, 6.95178442e-310],
        [6.95178442e-310, 6.95178442e-310, 1.10670705e-321]]])

In [27]:
np.empty_like(a)

array([[ 94180249512944,  94180258749456,               0],
       [              0,               0,               0],
       [              0,               0, 140705683045360],
       [              0,               0,  94180224143216],
       [ 94180224143216, 140704914826976, 140705683264432],
       [ 94180224279296,               0, 140704921918352],
       [140704914853232, 140704907350336,  94180224156224],
       [140705683045168, 140705683044144, 140705683054896],
       [140705683045488, 140705683042480,             224]])

In [28]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
np.identity??

# Data Types for ndarrays

In [33]:
a = np.arange(1,13, dtype='int')
print(a.dtype)

int64


In [34]:
a = np.arange(1,13, dtype=np.int64)
print(a.dtype)

int64


In [36]:
a = np.arange(1,13, dtype='i8')
print(a.dtype)

int64


In [40]:
a = a.astype(np.float64)
print(a.dtype)

float64


In [45]:
a = np.arange(1,28, dtype='g').reshape((3,3,3))
print(a)
print(a.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]
float128


In [46]:
np.full_like(a, 5, dtype=a.dtype)

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]], dtype=float128)

In [47]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [49]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [50]:
a[a % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
a[(a%3==0) | (a%5==0)]

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20, 21, 24, 25, 27])

In [53]:
a[(a%3==0) & (a%5==0)]

array([15])

In [56]:
a[~(a%3==0)]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [57]:
a[(~a%3==0)]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [61]:
a = np.array([1,3,5,6,8])
b = np.array([True, False, True,False,False])
a[~b]

array([3, 6, 8])

In [62]:
a = np.array([1,3,5,6,8])
b = [True, False, True,False,False]
a[~b]

TypeError: bad operand type for unary ~: 'list'

# Basic Indexing and Slicing

# Class4

* stacking
* split
* important methods

In [4]:
import numpy as np

a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [5]:

a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [6]:

a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b), axis=1)

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [24]:

a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.stack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
print(np.stack((a,b), axis=1))
np.column_stack((a,b))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]
 [ 6 11]]


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [12]:
print(np.stack((a,b), axis=0))
np.row_stack((a,b))

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.hstack((a,b))

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [26]:
a = np.arange(1,7)
b = a + 5
print(a, b, sep='\n')

np.vstack((a,b))
#stack axis 0
#row_stack
#vstack

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [31]:
np.block([a,b]) # hstack, columstack

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [36]:
a = np.arange(1,2*2*2+1).reshape((2,2,2))
b = a + 5
print(a,b, sep='\n->Second\n')

np.dstack((a,b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
->Second
[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


array([[[ 1,  2,  6,  7],
        [ 3,  4,  8,  9]],

       [[ 5,  6, 10, 11],
        [ 7,  8, 12, 13]]])

In [38]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 3, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [39]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [40]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 6, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [41]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 5, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


ValueError: array split does not result in an equal division

In [43]:
a = np.arange(6*6).reshape(6,6)
print(a)
np.split(a, 2, axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [45]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [46]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.split(a, 2, axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

# Borad Casting

In [20]:
a = np.random.randint(1,10, size=(3,5))
a

array([[4, 8, 8, 6, 2],
       [1, 1, 1, 5, 2],
       [8, 9, 1, 3, 9]])

In [21]:
a + 5

array([[ 9, 13, 13, 11,  7],
       [ 6,  6,  6, 10,  7],
       [13, 14,  6,  8, 14]])

In [23]:
b = np.full_like(a, 5)
print(a, b, sep='\n')
a + b

[[4 8 8 6 2]
 [1 1 1 5 2]
 [8 9 1 3 9]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 9, 13, 13, 11,  7],
       [ 6,  6,  6, 10,  7],
       [13, 14,  6,  8, 14]])

# Table 4-6. Array set operations

In [47]:
a = np.random.randint(1,10, size=20)
a

array([9, 3, 8, 6, 9, 9, 1, 1, 7, 2, 9, 6, 8, 8, 9, 4, 5, 4, 6, 1])

In [48]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

[True if x in a else False for x in b]

[4 5 4 3 4 7 2 3 3 1 2 4 6 1 7 4 6 6 2 5]
[7 4 7 7 9]


[True, True, True, True, False]

In [52]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

np.in1d(b, a)

[4 5 6 5 8 7 8 7 6 3 7 9 9 6 2 2 3 5 5 9]
[5 1 5 5 8]


array([ True, False,  True,  True,  True])

In [53]:
print(a,b, sep='\n')

np.intersect1d(b, a)print(a,b, sep='\n')

np.intersect1d(b, a)

[4 5 6 5 8 7 8 7 6 3 7 9 9 6 2 2 3 5 5 9]
[5 1 5 5 8]


array([5, 8])

In [70]:
c = np.in1d(b, a)
c = c.reshape((1,-1))
c
# np.apply_along_axis(lambda x:"A" if x else "B",1,arr=c)
np.where(c==True,"A","B")

array([['A', 'A', 'A', 'B', 'A']], dtype='<U1')

In [68]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')

["A" if x in a else "B" for x in b]

[8 3 9 7 2 5 1 4 4 4 7 8 2 1 8 8 9 5 8 5]
[3 9 7 6 7]


['A', 'A', 'A', 'B', 'A']

In [75]:
a = np.random.randint(1,10, size=20)
b =  np.random.randint(1,10, size=5)
print(a,b, sep='\n')
np.setdiff1d(b, a)

[7 6 7 7 5 8 7 8 3 8 9 7 2 7 2 5 9 3 2 6]
[8 5 3 5 4]


array([4])

In [76]:
#XOR
# 0 0 ->0
# 1 0 ->1
# 0 1 ->1
# 1 1 ->0
print(a,b, sep='\n')
np.setxor1d(b, a)

[7 6 7 7 5 8 7 8 3 8 9 7 2 7 2 5 9 3 2 6]
[8 5 3 5 4]


array([2, 4, 6, 7, 9])

In [80]:
np.save("abc.npy", a)