In [1]:
import numpy as np

In [2]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [6]:
a.shape = (3,9)

In [7]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [8]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones((3,3,3,3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [12]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [13]:
np.empty((2,2))

array([[4.679541e-310, 0.000000e+000],
       [0.000000e+000,           nan]])

In [14]:
np.empty_like(a)

array([[94714964553936,              0,              0,              0,
                     0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0,              0,              0,              0,
                     0],
       [             0,              0,              0,              0,
                     0,              0,              0,              0,
                     0]])

In [15]:
np.full((2,3,3), fill_value=5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [16]:
np.full_like(a, 7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [17]:
np.ones((2,3)) * 7

array([[7., 7., 7.],
       [7., 7., 7.]])

In [21]:
np.ones_like(a, dtype=np.float64)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye??

In [22]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.identity??

In [ ]:
from numpy import random

# Data Types for ndarrays

In [35]:
#reshape(astype(range(1,12)))
a = np.arange(1,13).astype(np.float64).reshape((3,4))
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [36]:
a = np.arange(1,13).reshape((3,4)).astype(np.float64)
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [44]:
a = np.arange(1,13).astype(np.character).reshape((3,4))
a

array([[b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8'],
       [b'9', b'10', b'11', b'12']], dtype='|S21')

In [40]:
a = np.arange(1,13, dtype="character").reshape((3,4))
a

TypeError: data type "character" not understood

In [45]:
a = np.array([1,2,4], dtype=np.float32)
a

array([1., 2., 4.], dtype=float32)

In [46]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [48]:
print(a.dtype)
print(arr2.dtype)

float32
int32


In [49]:
print(type(a))
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [55]:
a = np.array([1,2,3], dtype='int')
print(a.dtype)

a = np.array([1,2,3], dtype=np.int64)
print(a.dtype)
a = np.array([1,2,3], dtype='i8')
print(a.dtype)

int64
int64
int64


In [56]:
def abc(x):
    try:
        x = str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
    
abc("kjadjslkljskldksljkl3askjd-asdfl;ak3")    

33

In [57]:
a = np.arange(1,12, dtype=np.float64)
b = np.arange(1,4)
print(a.dtype)
print(b.dtype)

float64
int64


In [58]:
b.astype(a.dtype)

array([1., 2., 3.])

In [59]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [60]:
a % 5 == 0

array([[[False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[ True, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [ True, False, False]]])

In [61]:
a[a % 5 == 0]

array([ 5, 10, 15, 20, 25])

In [62]:
a[(a%5==0) & (a%3==0)]

array([15])

In [63]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [71]:
a[1][1][1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [69]:
a[1:,1:,:1]

array([[[13],
        [16]],

       [[22],
        [25]]])

In [72]:
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int64)

In [76]:
a[1:][1:][1:]

array([], shape=(0, 3, 3), dtype=int64)

In [70]:
a[1,1,1]

14

# Class3

In [1]:
l = [1,3,4,8,9]
l[:2] = 5

TypeError: can only assign an iterable

In [2]:
import numpy as np

In [3]:
l = np.array([1,3,4,8,9])
l[:2] = 5
l

array([5, 5, 4, 8, 9])

In [4]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
print(a[:2])
print(a[0:2])
print(a[-3:2])
print(a[-3:-1])

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [10]:
data = np.random.randn(7, 4)
data

array([[ 0.58803134, -0.50694419,  0.31284521, -0.043329  ],
       [-1.2410737 ,  1.27696511,  0.1975464 ,  0.42316356],
       [ 2.25186106, -0.73471444,  1.22905028, -0.19440093],
       [ 0.13626753,  0.90692052,  0.1527486 , -0.26967539],
       [ 0.84318343,  1.51099296,  0.06540767,  0.64077727],
       [-1.21153767,  0.99996934,  0.34614855, -1.9707386 ],
       [ 0.30147468, -1.18281944, -1.08085896, -0.73266897]])

In [13]:
data[names == "Bob"]

array([[ 0.58803134, -0.50694419,  0.31284521, -0.043329  ],
       [ 0.13626753,  0.90692052,  0.1527486 , -0.26967539]])

In [18]:
data[(names=="Bob") | (names=="Will")][:,[0,-1]]

array([[ 0.58803134, -0.043329  ],
       [ 2.25186106, -0.19440093],
       [ 0.13626753, -0.26967539],
       [ 0.84318343,  0.64077727]])

In [27]:
data[(names=="Bob") | (names=="Will")][:,[0,-1]]

array([[0.58803134, 0.        ],
       [2.25186106, 0.        ],
       [0.13626753, 0.        ],
       [0.84318343, 0.64077727]])

In [21]:
print(data)# arr[[rows], [cols]]
# data[[0,-1,3]]
data[:,[0,-1]]

[[ 0.58803134 -0.50694419  0.31284521 -0.043329  ]
 [-1.2410737   1.27696511  0.1975464   0.42316356]
 [ 2.25186106 -0.73471444  1.22905028 -0.19440093]
 [ 0.13626753  0.90692052  0.1527486  -0.26967539]
 [ 0.84318343  1.51099296  0.06540767  0.64077727]
 [-1.21153767  0.99996934  0.34614855 -1.9707386 ]
 [ 0.30147468 -1.18281944 -1.08085896 -0.73266897]]


array([[ 0.58803134, -0.043329  ],
       [-1.2410737 ,  0.42316356],
       [ 2.25186106, -0.19440093],
       [ 0.13626753, -0.26967539],
       [ 0.84318343,  0.64077727],
       [-1.21153767, -1.9707386 ],
       [ 0.30147468, -0.73266897]])

In [24]:
data[data < 0] = 0
data

array([[0.58803134, 0.        , 0.31284521, 0.        ],
       [0.        , 1.27696511, 0.1975464 , 0.42316356],
       [2.25186106, 0.        , 1.22905028, 0.        ],
       [0.13626753, 0.90692052, 0.1527486 , 0.        ],
       [0.84318343, 1.51099296, 0.06540767, 0.64077727],
       [0.        , 0.99996934, 0.34614855, 0.        ],
       [0.30147468, 0.        , 0.        , 0.        ]])

## Fancy Slicing

In [30]:
print(data)
print()
print(data[:,[-2,0,-1]])

[[0.58803134 0.         0.31284521 0.        ]
 [0.         1.27696511 0.1975464  0.42316356]
 [2.25186106 0.         1.22905028 0.        ]
 [0.13626753 0.90692052 0.1527486  0.        ]
 [0.84318343 1.51099296 0.06540767 0.64077727]
 [0.         0.99996934 0.34614855 0.        ]
 [0.30147468 0.         0.         0.        ]]

[[0.31284521 0.58803134 0.        ]
 [0.1975464  0.         0.42316356]
 [1.22905028 2.25186106 0.        ]
 [0.1527486  0.13626753 0.        ]
 [0.06540767 0.84318343 0.64077727]
 [0.34614855 0.         0.        ]
 [0.         0.30147468 0.        ]]


In [34]:
print(data)
print()
print(data[0,0])

[[0.58803134 0.         0.31284521 0.        ]
 [0.         1.27696511 0.1975464  0.42316356]
 [2.25186106 0.         1.22905028 0.        ]
 [0.13626753 0.90692052 0.1527486  0.        ]
 [0.84318343 1.51099296 0.06540767 0.64077727]
 [0.         0.99996934 0.34614855 0.        ]
 [0.30147468 0.         0.         0.        ]]

0.5880313400152156


In [36]:
a = np.zeros((8,4))
print(a)

for i, v in enumerate(a):
    a[i] = i
a    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
a = np.zeros((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
a    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [39]:
a = np.zeros((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
a    

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
print(a)
print()
print(a.T)
print()
print(a.transpose())

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]

[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]


In [47]:
a = np.array([[1,2],
             [3,4]])

b = np.array([[5,6],
             [7,8]])

print(a,b ,sep="\n\n", end="\n\n")

print( a * b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [48]:
print( a @ b)

[[19 22]
 [43 50]]


In [49]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [54]:
arr = np.arange(10, 2*2*4+10).reshape((2, 2, 4))
arr

array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [52]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [55]:
print(arr)
arr.transpose((1, 0, 2))

[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 11, 12, 13],
        [18, 19, 20, 21]],

       [[14, 15, 16, 17],
        [22, 23, 24, 25]]])

In [57]:
print(arr)
arr.swapaxes(1, 2)


[[[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]


array([[[10, 14],
        [11, 15],
        [12, 16],
        [13, 17]],

       [[18, 22],
        [19, 23],
        [20, 24],
        [21, 25]]])

In [59]:
a = np.arange(3*4).reshape((3,4))
print(a)

a.swapaxes(1,0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
arr.transpose??

## 4.2 Universal Functions: Fast Element-Wise Array Functions

In [60]:
a = np.array([1,2,-3,4,-5,7,9])
print(np.abs(a))

[1 2 3 4 5 7 9]


In [61]:
a = np.array([1,2,-3,4,-5,7,9])
print(np.fabs(a))

[1. 2. 3. 4. 5. 7. 9.]


In [62]:
np.exp??

In [64]:
a = np.array([1.27, 3.9, 9.2])
f, w = np.modf(a)
print(w,f, sep="\n")

[1. 3. 9.]
[0.27 0.9  0.2 ]


In [67]:
a = np.array([11,20,25])
np.fmod(a,3)

array([2, 2, 1])

In [72]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.maximum(a,b)


array([1, 5, 7])

In [73]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.minimum(a,b)

array([-1,  2,  3])

In [75]:
a = np.array([1,2,3])
b = np.array([-1,5,7])

np.fmax(a,b)

array([1, 5, 7])

# 4.3 Array-Oriented Programming with Arrays

In [79]:
a = np.arange(3*2).reshape((3,2))
print(a)

print(np.meshgrid(a,a))

[[0 1]
 [2 3]
 [4 5]]
[array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]]), array([[0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5]])]


In [80]:
a = np.arange(36)
a % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False])

In [81]:
a = np.arange(36)
#np.where(condition, true_value, false_value)
np.where(a%3==0, "yes","no")

array(['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes',
       'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no',
       'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no',
       'yes', 'no', 'no', 'yes', 'no', 'no'], dtype='<U3')

# Mathematical and Statistical Methods

In [83]:
a = np.arange(3*4).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [84]:
np.sum(a)

66

In [85]:
a = np.arange(3*4).reshape((3,4))
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [86]:
a = np.arange(3*4).reshape((3,4))
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

In [87]:
a = np.array([1,3,6,8,20,2,3])
np.argmax(a)

4

In [88]:
np.argsort(a)

array([0, 5, 1, 6, 2, 3, 4])

In [ ]:
Linag
Universal function
stack,
in1d, in

In [90]:
import sys
import numpy as np
import leastsquares


def main():
    dataFn = sys.argv[1]
    data = np.genfromtxt(dataFn, delimiter=',')
    a,b,c = leastsquares.findCoefficients(data)
    print("a=",a)
    print("b=",b)
    print("c=",c)

if __name__ == "__main__":
    main()

OSError: -f not found.

# class3

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 20, size=20)
b = np.random.randint(1,10, size=10)
print(a, b, sep="\n\n")

[18 13 15 19  9 18  9  6 18 17 14 18 16  6  2 15 10 12 17 12]

[8 9 6 1 2 9 4 7 6 7]


In [3]:
[True if x in a else False for x in b]

[False, True, True, False, True, True, False, False, True, False]

In [4]:
np.in1d(b, a)

array([False,  True,  True, False,  True,  True, False, False,  True,
       False])