In [3]:
import numpy as np

In [4]:
np.sum([1,3])

4

In [1]:
sum([1,3])

4

In [2]:
def abc():
    print("hello")
    
def abc():
    print("Pakistan")
    
abc()    

Pakistan


In [5]:
np.__version__

'1.18.2'

In [6]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in /home/muhammadqasim/anaconda3/lib/python3.7/site-packages (1.18.2)


In [7]:
%history

sum([1,3])
def abc():
    print("hello")
    
def abc():
    print("Pakistan")
    
abc()
import numpy as np
np.sum([1,3])
np.__version__
!pip install --upgrade numpy
%history


In [9]:
%time list(range(2000000))[:20]

CPU times: user 65.9 ms, sys: 29.6 ms, total: 95.4 ms
Wall time: 124 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [10]:
%time np.arange(2000000)

CPU times: user 6.29 ms, sys: 1.17 ms, total: 7.46 ms
Wall time: 12.7 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [12]:
%time [x+5 for x in range(1,1000000)][:20]

CPU times: user 83.8 ms, sys: 7.2 ms, total: 91 ms
Wall time: 103 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

In [26]:
l = list(range(1,1000000))
l2 = list(enumerate(l))
for i, v in l2:
    l[i] = l[i]+5
l[:20] 
%time

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.29 µs


In [47]:
# Two Dimension list adding value 5 

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Before Adding 5")
print(a)
print()
for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c] + 5
        
print("After Adding 5")        
print(a) 

Before Adding 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After Adding 5
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [48]:
a = np.arange(1,10).reshape((3,3))
a = a+5
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [52]:
a = np.arange(1,28).reshape((3,3,3))
a = a+5
a

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32]]])

In [61]:
a = np.arange(1,28).reshape((3,3,3))
a = a%2
a

array([[[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]],

       [[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]]])

In [70]:
a = np.random.randn(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a = a * 10
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[-8.18608497e+00,  1.12245097e+01,  9.80636997e+00,
             6.57779425e-01,  1.33920551e+01],
           [-1.18921168e+01,  1.91706719e+01, -4.43400706e+00,
            -2.09807690e+00,  5.68126605e+00],
           [ 1.74191632e+00, -7.46298748e-01,  5.50092660e+00,
             2.30363313e+00,  1.38784392e+01],
           [ 8.30412441e+00, -1.87947677e+01,  1.60181280e+01,
            -1.88231455e+01, -3.70778233e+00],
           [ 7.65836609e+00, -4.81892368e+00, -2.56868283e+00,
            -1.57092323e+01, -3.60794321e-01]],

          [[ 7.05429794e+00,  1.00844285e+00,  4.18477595e+00,
             1.05626284e+01, -8.18716765e+00],
           [-2.12682928e+01, -9.72697841e+00, -1.40045099e+01,
            -9.90643775e+00,  9.12048391e+00],
           [ 1.36749999e+00,  1.13220459e+01, -4.84376191e+00,
             1.75110522e+01, -6.26528004e+00],
           [-4.39289042e+00,  1.24538086e+01,  1.50087689e+00,
             1.23440214e+00,  1.20980046e+01],
        

In [75]:
a = np.arange(1,13).reshape((6,2))
print(a)

print(a * a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[  1   4]
 [  9  16]
 [ 25  36]
 [ 49  64]
 [ 81 100]
 [121 144]]


# a[i,j,k]

In [55]:
#a[2]
#a[2,0]
a[2,0,1]

25

<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [27]:
l = np.arange(1,1000000)
l = l + 5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [28]:
type(l)

numpy.ndarray

In [29]:
l.shape

(999999,)

In [31]:
l.ndim

1

# Dimensions

In [33]:
a = np.array([1])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1]
1
(1,)
int64


In [34]:
a = np.array([1,2,4,5])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 4 5]
1
(4,)
int64


In [36]:
a = np.array([[1,2,4],
              [3,5,6],
              [2,1,5]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[1 2 4]
 [3 5 6]
 [2 1 5]]
2
(3, 3)
int64


# Creating ndarrays

In [78]:
a = [1,2,3]
print(type(a))

a = np.array(a)
type(a)


<class 'list'>


numpy.ndarray

In [79]:
a = (1,2,3)

print(type(a))

a = np.array(a)
type(a)

<class 'tuple'>


numpy.ndarray

In [80]:
a = {1,2,3}
print(type(a))

a = np.array(a)
type(a)

<class 'set'>


numpy.ndarray

# np.array

In [83]:
l = [1,2,3]
a = np.array(l)
b = np.array(a)
a is b

False

### np.asarray

In [84]:
l = [1,2,3]
a = np.asarray(l)
b = np.asarray(a)
a is b

True