In [3]:
%history

%history
print("Helloworld")
%history


In [2]:
print("Helloworld")

Helloworld


In [4]:
print("Line1")
print("Line2")

Line1
Line2


In [ ]:
# %load fileName.py
print("Line1")
print("Line2")


In [6]:
%run fileName.py

Line1
Line2


In [7]:
%time print("ada")

ada
CPU times: user 506 µs, sys: 136 µs, total: 642 µs
Wall time: 649 µs


# Python

In [14]:
%time l1 = list(range(1,3000000))
print(l1[:10])

CPU times: user 85.3 ms, sys: 52.8 ms, total: 138 ms
Wall time: 154 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
%time [x+5 for x in l1][:10]

CPU times: user 258 ms, sys: 71 ms, total: 329 ms
Wall time: 489 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [20]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [21]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [22]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [25]:
l1 = [1,2,4]
l1 + 5

TypeError: can only concatenate list (not "int") to list

# Numpy 

In [1]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [11]:
#import numpy as *
import numpy as np

In [12]:
l = [1,3,2]
print(sum(l))
print(np.sum(l))

6
6


In [24]:
l1 = np.arange(1,3000000)
%time l1 + 5

CPU times: user 10.3 ms, sys: 642 µs, total: 10.9 ms
Wall time: 12.7 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [26]:
l1 = np.arange(1,13)

print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

Diminsion: 1
Type: int64
Size: 12
Itemsize: 8
Shape: (12,)


# A Multidimensional Array Object

In [34]:
#l1 = np.arange(1,13).reshape((4,3))
#l1 = np.arange(1,13).reshape((3,4))
#l1 = np.arange(1,13).reshape((2,6))
#l1 = np.arange(1,13).reshape((6,2))
l1 = np.arange(1,13).reshape((12,1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Diminsion: 2
Type: int64
Size: 12
Itemsize: 8
Shape: (12, 1)


<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [36]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [40]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
#l1[1]
#l1[1,2]
l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [42]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [43]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[-1.64862618e-01 -1.06401826e+00 -9.38454295e-01]
  [-1.28984536e+00 -5.75264216e-01 -1.48039211e-01]
  [-1.45804769e-01 -1.36227695e+00  4.27366617e-01]]

 [[ 1.98609550e+00 -4.98817498e-02 -1.55501169e-03]
  [-2.86247610e-03 -1.19001345e+00 -5.44593586e-01]
  [-1.22419921e+00  3.45676982e-01  5.35868746e-01]]

 [[ 9.75875944e-01 -2.10176417e+00  9.16510518e-01]
  [ 2.94217262e-01  8.58220098e-02  2.53974536e+00]
  [-1.72470622e+00  9.32735433e-01 -6.26833771e-01]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [51]:
#l1 + 2
#l1 * 2
#l1 / 2
#l1 ** 2
#l1 ** 0.5
#l1 % 2

array([[[-3.29725237e-01, -2.12803651e+00, -1.87690859e+00],
        [-2.57969072e+00, -1.15052843e+00, -2.96078422e-01],
        [-2.91609539e-01, -2.72455390e+00,  8.54733233e-01]],

       [[ 3.97219100e+00, -9.97634995e-02, -3.11002338e-03],
        [-5.72495220e-03, -2.38002689e+00, -1.08918717e+00],
        [-2.44839842e+00,  6.91353963e-01,  1.07173749e+00]],

       [[ 1.95175189e+00, -4.20352834e+00,  1.83302104e+00],
        [ 5.88434524e-01,  1.71644020e-01,  5.07949072e+00],
        [-3.44941244e+00,  1.86547087e+00, -1.25366754e+00]]])

# Creating ndarrays

##### np.array()

In [52]:
# Deep Copy(Always copy)
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #True

False
False


In [54]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [3]:
import numpy as np
a = np.array([1,2])
a.itemsize

8

# Class 2

In [1]:
import numpy as np

## Creating ndarrays

In [2]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])

In [4]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Chaining

In [7]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [9]:
C(B(A(1)))

19

In [10]:
A(B(C(1)))

19

In [ ]:
np.A().B().C()

In [ ]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [12]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
a = np.reshape(np.arange(1,28), (3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [18]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [23]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [26]:
a.shape

(9, 3)

In [21]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [31]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [35]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [37]:
b = np.full_like(a, 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [38]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [41]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [45]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [46]:
np.empty_like(a)

array([[4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528]])

In [51]:
np.full_like(a, 1) * np.nan


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [53]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [55]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [58]:
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int64')

In [65]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int64')

In [59]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [61]:
a = np.array([1,3,4], dtype='i8')
a.dtype

dtype('int64')

In [63]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int64')

In [64]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

# Boolen Operation

In [66]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [ ]:
print(a)
a[a%3==0]

In [74]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [75]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [76]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [77]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [78]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# Fancy Slicing

In [1]:
import numpy as np

In [6]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[1,2,0]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [25]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
#print(a[[1,2,0]])
#print(a[[1,2,0]])
#a[[1,2,0],[0,1,2],]
a[[1,2,0]][:,[0,1,2]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [29]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-1.39922186 -0.16334857  1.3046131   0.26681035]
 [ 1.29527552  0.21563346 -1.18805261 -0.1364378 ]
 [-0.40840862  0.83691235  1.50680745 -0.845101  ]
 [-0.86596367  0.57109951  0.06941386 -0.54217647]
 [ 0.44679608  0.59369333 -1.08288186 -1.30909242]
 [-1.28403348  1.31270803  0.58549244 -0.93168243]]


In [30]:
names == "Qasim"

array([ True, False, False, False,  True, False])

In [31]:
data[[ True, False, False, False,  True, False]]

array([[-1.39922186, -0.16334857,  1.3046131 ,  0.26681035],
       [ 0.44679608,  0.59369333, -1.08288186, -1.30909242]])

In [32]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

print()
data[names=="Qasim"]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.22474157  0.50530887  0.06613031 -0.59611273]
 [-0.32733532  0.99971797  0.80923505 -1.85539616]
 [ 0.48982313 -0.3250227  -0.60791202 -0.85967758]
 [-0.51170764  0.85387473 -0.66134088 -0.19928265]
 [ 1.27090135 -1.44944336  1.81183635  0.35846498]
 [ 1.19495689  1.65506477  1.26452383  1.83447206]]



array([[-0.22474157,  0.50530887,  0.06613031, -0.59611273],
       [ 1.27090135, -1.44944336,  1.81183635,  0.35846498]])

In [44]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.50774034 -1.23782354 -1.76013953  0.24135854]
 [-1.13306306  1.5972504  -0.17143635 -1.51057288]
 [-1.76653562  0.58349036  0.42735807 -1.63385416]
 [ 0.82459197  0.44196116 -1.10006245 -0.05300363]
 [-0.90818883 -0.10973842  0.46215395 -1.83130673]
 [ 0.31481636 -0.50441725  0.67355392 -0.09033001]]


array([[ 0.50774034, -1.23782354, -1.76013953,  0.24135854],
       [ 0.82459197,  0.44196116, -1.10006245, -0.05300363],
       [-0.90818883, -0.10973842,  0.46215395, -1.83130673]])

In [45]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names!="Qasim") |  (names!="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.68625744 -0.28474352  0.08050751  0.58190465]
 [-0.59722899  0.12751042  0.0436271   0.10720398]
 [ 0.5235168   0.9833551   0.37980503 -0.04902237]
 [ 0.29991175  0.78133878 -0.37425787 -1.2431577 ]
 [ 1.13913888 -0.04536789 -0.94405513  0.35861   ]
 [ 0.89761815  0.48589357  0.8750981  -0.03913017]]


array([[ 0.68625744, -0.28474352,  0.08050751,  0.58190465],
       [-0.59722899,  0.12751042,  0.0436271 ,  0.10720398],
       [ 0.5235168 ,  0.9833551 ,  0.37980503, -0.04902237],
       [ 0.29991175,  0.78133878, -0.37425787, -1.2431577 ],
       [ 1.13913888, -0.04536789, -0.94405513,  0.35861   ],
       [ 0.89761815,  0.48589357,  0.8750981 , -0.03913017]])

In [47]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 1.25912266  0.37503825 -0.18941131 -0.69179118]
 [ 0.89822488  0.6840981   0.20819676  2.11829874]
 [ 1.96117666  0.79650812  2.18242632  0.22992232]
 [ 1.30489563  1.95970012  0.06966132 -0.40207016]
 [ 0.481564   -0.09452716 -0.96143653 -0.82370543]
 [-2.04525757  0.41177263 -1.41501135  0.76988411]]


array([[ 1.25912266, -0.69179118],
       [ 1.30489563, -0.40207016],
       [ 0.481564  , -0.82370543]])

In [49]:
l = [1,3,5,3,5]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [51]:
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5
l

array([5, 5, 5, 3, 5])

In [53]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [54]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [56]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [57]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


# Transposing Arrays and Swapping Axes

In [61]:
a = np.arange(4*3).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [62]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [64]:
a.T.T.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [65]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [67]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

In [68]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [69]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [70]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [72]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [73]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [76]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

# Table 4-3. Unary ufuncs

In [77]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a)

array([ 7,  8, 20,  2,  3, 20])

In [78]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

array([ 7.,  8., 20.,  2.,  3., 20.])

In [80]:
a = np.array([36,25,16])
np.fabs(a)

array([36., 25., 16.])

In [81]:
a = np.array([7,8,-20,2,-3,20])
np.square(a)

array([ 49,  64, 400,   4,   9, 400])

In [82]:
np.exp(a)

array([1.09663316e+03, 2.98095799e+03, 2.06115362e-09, 7.38905610e+00,
       4.97870684e-02, 4.85165195e+08])

In [83]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [84]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [85]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [86]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [89]:
np.isnan(np.nan)

True

In [90]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.maximum(a,b)

array([3, 3, 5, 7])

In [91]:
np.fmax(a,b)

array([3, 3, 5, 7])

# 4.3 Array-Oriented Programming with Arrays

In [94]:
a = np.arange(4*3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [95]:
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

#### np.wher(condition, value_true, value_false)

In [96]:
a = np.arange(8*4).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [97]:
np.where(a%3 == 0, "Yes","No")

array([['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No']], dtype='<U3')

In [98]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

array([3, 3, 5, 7])

# Mathematical and Statistical Methods

In [100]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.sum(a)

66

In [102]:
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [103]:
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

# class 4 

##### Broad Casting

In [5]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 5)
print(a,b,sep="\n\n")
a + b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## stacking

#### split

# > Stackig

In [13]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[9 2 1 9 6 9 2 5 9 2]
[14  7  6 14 11 14  7 10 14  7]
10 10


In [14]:
print(a,b, sep='\n\n')

[9 2 1 9 6 9 2 5 9 2]

[14  7  6 14 11 14  7 10 14  7]


In [15]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

[9 2 1 9 6 9 2 5 9 2]

[14  7  6 14 11 14  7 10 14  7]


array([[ 9,  2,  1,  9,  6,  9,  2,  5,  9,  2],
       [14,  7,  6, 14, 11, 14,  7, 10, 14,  7]])

In [16]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

[9 2 1 9 6 9 2 5 9 2]

[14  7  6 14 11 14  7 10 14  7]


array([[ 9, 14],
       [ 2,  7],
       [ 1,  6],
       [ 9, 14],
       [ 6, 11],
       [ 9, 14],
       [ 2,  7],
       [ 5, 10],
       [ 9, 14],
       [ 2,  7]])

In [17]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

array([[ 9, 14],
       [ 2,  7],
       [ 1,  6],
       [ 9, 14],
       [ 6, 11],
       [ 9, 14],
       [ 2,  7],
       [ 5, 10],
       [ 9, 14],
       [ 2,  7]])

In [19]:
# np.stack((a,b), axis=0)
# np.vstack((a,b))
np.row_stack((a,b))

array([[ 9,  2,  1,  9,  6,  9,  2,  5,  9,  2],
       [14,  7,  6, 14, 11, 14,  7, 10, 14,  7]])

In [20]:
np.hstack((a,b))

array([ 9,  2,  1,  9,  6,  9,  2,  5,  9,  2, 14,  7,  6, 14, 11, 14,  7,
       10, 14,  7])

In [21]:
np.vstack((a,b))

array([[ 9,  2,  1,  9,  6,  9,  2,  5,  9,  2],
       [14,  7,  6, 14, 11, 14,  7, 10, 14,  7]])

In [23]:
b = np.arange(3*3).reshape((3,3)) 
a = a + 5
print(a, b, sep='\n\n')

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
np.row_stack((a,b))

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [25]:
np.vstack((a,b))

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [26]:
np.hstack((a,b))

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [27]:
np.column_stack((a,b))

array([[ 5,  6,  7,  0,  1,  2],
       [ 8,  9, 10,  3,  4,  5],
       [11, 12, 13,  6,  7,  8]])

In [30]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1,  7,  8],
        [ 2,  3,  9, 10]],

       [[ 4,  5, 11, 12],
        [ 6,  7, 13, 14]]])

In [33]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.stack((a,b), axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[[ 0,  1],
         [ 7,  8]],

        [[ 2,  3],
         [ 9, 10]]],


       [[[ 4,  5],
         [11, 12]],

        [[ 6,  7],
         [13, 14]]]])

In [34]:
np.stack??

In [37]:
a.reshape((2,-1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Split

In [42]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=0)
np.split(a, 3, axis=0)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [44]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=1)
np.split(a, 3, axis=1)
np.split(a, 2, axis=1)[0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

In [51]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

# Table 4-6. Array set operations

In [55]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[6 9 5 9 8 8 2 6 7 5 6 3 8 8 5 5 7 3 6 2]


array([2, 3, 5, 6, 7, 8, 9])

In [58]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


In [63]:
[True if x in piaic else False for x in cnic]

[True, True, True, False, True]

In [64]:
[x in piaic for x in cnic]

[True, True, True, False, True]

In [65]:
["Yes" if x in piaic else "NO" for x in cnic]

['Yes', 'Yes', 'Yes', 'NO', 'Yes']

In [67]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)


[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array([ True,  True,  True, False,  True])

In [69]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
np.where(c==True,"Yes","No")

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array(['Yes', 'Yes', 'Yes', 'No', 'Yes'], dtype='<U3')

In [71]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array([4, 6, 8])

In [72]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array([ 2,  4,  6,  8,  9, 10, 27, 28, 31, 37, 38, 44, 45, 49, 53, 58, 61,
       63, 66, 75, 78, 79, 81, 82, 91, 98])

In [73]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array([9])

In [74]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)

[28 28 53 58  8 31 79  4 10 49 45 63 78 82 98 27 81 61 91 38 10  2 66 91
 58 79 37  6 44 75]

[8 4 6 9 8]


array([ 2,  9, 10, 27, 28, 31, 37, 38, 44, 45, 49, 53, 58, 61, 63, 66, 75,
       78, 79, 81, 82, 91, 98])