In [3]:
%history

%history
sum([1,3,2])
%history


In [4]:
!touch fileName.py

In [ ]:
# %load fileName.py
print("Line1")
print("Line2")


In [6]:
%run fileName.py

Line1
Line2


In [7]:
%time sum([1,3,4])

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 14.8 µs


8

In [2]:
sum([1,3,2])

6

## Python Vs Numpy

In [13]:
%time l1 = list(range(1,3000000))

CPU times: user 79 ms, sys: 42.2 ms, total: 121 ms
Wall time: 127 ms


In [16]:
%time [x+5 for x in l1][:10]

CPU times: user 171 ms, sys: 98.1 ms, total: 269 ms
Wall time: 311 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [18]:
list(enumerate(['A','B',"C"]))

[(0, 'A'), (1, 'B'), (2, 'C')]

In [24]:
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]    

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [26]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print(a)
for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        

print("After Adding 5")
print(a)        

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [28]:
a = [1,2,3]
a + 5

TypeError: can only concatenate list (not "int") to list

#### numpy

In [1]:
import numpy as np

In [32]:
%time l2 = np.arange(1,3000000)

CPU times: user 2.2 ms, sys: 32.1 ms, total: 34.3 ms
Wall time: 44.7 ms


In [34]:
l1 = np.array([1])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

Dimension: 1
Shape: (2999999,)
Type: int64


In [38]:
l1 = np.random.randn(2,2)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]

[[1.47125843 2.49071193]
 [0.10666251 0.12005191]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [40]:
l1 = np.random.randn(3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[[-0.92403551 -0.19492633  0.07289328]
  [-0.80882656 -0.23839292 -0.01752686]
  [-0.33669569 -1.15779816  1.67631527]]

 [[ 0.38361036  0.65650523  0.50043071]
  [-0.88004281  0.31530807 -0.22970217]
  [-0.84590703  0.93786127  0.26952903]]

 [[ 1.14188197  0.55539167 -0.16307304]
  [ 0.51320962 -0.51096165 -2.67776784]
  [ 0.884293    0.6102596  -0.04489273]]]
Dimension: 3
Shape: (3, 3, 3)
Type: float64


In [45]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

l1[1,2,1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int64


16

<img src='https://www.pythoninformer.com/img/numpy/3d-array.png'>

In [ ]:
l1[i,j,k]

In [46]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)

l1 = l1 + 5
l1

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

# A Multidimensional Array Object

In [48]:
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int64


In [61]:
l1 = np.arange(1,26).reshape((5,5))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int64


In [58]:
l1 = np.random.randn(3,3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize)
print("Type:", l1.dtype)

[[[[[ 2.17997245e-01  1.17636034e-01 -1.88043211e-01]
    [-8.38270977e-01  5.73058264e-01  2.62179000e+00]
    [ 2.94423466e-01  1.26342188e+00 -1.11420967e+00]]

   [[ 1.41217879e-01  8.41753583e-01 -2.09826989e-01]
    [-6.47256815e-01  6.72733701e-01 -4.23388019e-01]
    [-3.57643586e-01  3.65479467e-01  1.82631594e-01]]

   [[-1.20782230e+00  5.24708364e-01 -2.28088869e-01]
    [-5.28284704e-01 -1.51464487e-01 -1.68459793e+00]
    [ 1.03134214e+00 -3.40389256e-01  1.15188231e+00]]]


  [[[-9.21864497e-01  1.76824878e+00  3.24093256e-01]
    [ 3.57961717e-01  1.07922793e+00 -4.53412373e-02]
    [-2.39591182e-01  2.94417738e-01  6.52140946e-01]]

   [[-1.38735478e+00  3.61815140e-01  8.14982045e-01]
    [ 3.73525987e-01  2.63650414e-02  5.71849998e-02]
    [ 1.04681139e+00 -3.77448023e-01 -4.05741767e-01]]

   [[ 5.97876454e-01 -1.20072196e+00 -1.00081816e+00]
    [ 4.90401155e-01  1.57397803e-02  6.69907507e-01]
    [ 9.68350211e-01  1.86170697e+00  4.38177477e-01]]]


  [[[ 6.5127

In [69]:
a = np.arange(1,28).reshape((3,3,3))
print(a ** .5)

[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]
  [2.64575131 2.82842712 3.        ]]

 [[3.16227766 3.31662479 3.46410162]
  [3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069]]

 [[4.35889894 4.47213595 4.58257569]
  [4.69041576 4.79583152 4.89897949]
  [5.         5.09901951 5.19615242]]]


# Creating ndarrays

#### np.array

In [70]:
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)

<class 'list'>
False


numpy.ndarray

### np.asarray

In [73]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [74]:
%history

%history
sum([1,3,2])
%history
!touch fileName.py
%load fileName.py
%run fileName.py
%time sum([1,3,4])
%time l1 = list(range(1,2000000))
%time l1 = list(range(1,3000000))
import numpy as np
%time l1 = np.arange(1,2000000)
%time l2 = np.arange(1,2000000)
%time l1 = list(range(1,3000000))
l1[:10]
%time [x+5 for x in l1]
%time [x+5 for x in l1][:10]
enumerate(['A','B',"C"])
list(enumerate(['A','B',"C"]))
for i, v for list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
%time
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]

%time for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    %time l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print

In [3]:
a = np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
a.data

In [5]:
id(a)

140142119158288

# Class3

In [2]:
import numpy as np
a  = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
print(a[1,1,2])
print(a[1][1][2])
print(a[-2,-2,-1])

14
14
14


In [13]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-1.00823565  1.59065096  0.06204843 -0.97503396]
 [-0.12786759 -0.40388411  1.38899734 -0.1981959 ]
 [ 1.39458559 -1.09859069  1.28394802 -1.01427146]
 [ 0.01843606 -0.97718351  1.01636432  0.02457016]
 [-0.30932401 -0.98933129 -1.83143493 -1.47246756]
 [ 1.30992243 -0.13613971  1.80738146  0.4761625 ]]


In [14]:
names=="Qasim"

array([ True, False, False, False,  True, False])

In [15]:
data[[ True, False, False, False,  True, False]]

array([[-1.00823565,  1.59065096,  0.06204843, -0.97503396],
       [-0.30932401, -0.98933129, -1.83143493, -1.47246756]])

In [16]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)
print(names, data, sep="\n")

data[names=="Qasim"]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-1.11825062  0.15846794 -0.79024609  0.02215637]
 [ 0.27597623 -0.08621729 -0.08262871 -0.94681653]
 [ 0.77632894 -0.64460259 -0.84470545 -1.37783688]
 [ 0.74719609 -0.71333066 -0.37493361  0.68698723]
 [-0.29402428  0.37581761  0.94224619  0.45194765]
 [ 2.64795742 -0.20316616  0.25509219 -1.45671936]]


array([[-1.11825062,  0.15846794, -0.79024609,  0.02215637],
       [-0.29402428,  0.37581761,  0.94224619,  0.45194765]])

In [17]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

data[names=="Qasim"][:,[-1,0,2]]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-0.49706207 -1.28510521 -2.46578445  1.15377049]
 [-0.1466769   0.20616576  0.0788241   1.35977606]
 [ 0.34522842  0.3821182  -2.28386463 -0.19435333]
 [ 0.82223594  1.55856031  1.37903465 -1.44314583]
 [-1.99238107 -0.02339951  1.66213167  1.21416188]
 [ 1.47226935  1.47373532 -0.61532837  0.33542544]]


array([[ 1.15377049, -0.49706207, -2.46578445],
       [ 1.21416188, -1.99238107,  1.66213167]])

In [48]:
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])

data = np.random.randn(6,4)

print(names, data, sep="\n")

#data[~(names == "Qasim") | ~(names=="Ali")]
data[(names != "Qasim") | (names!="Ali")]
data[:,::-1]

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[-0.37300834 -1.63033151 -0.17379724 -0.52837376]
 [ 1.25120439 -0.40674631 -0.76328834 -0.6720027 ]
 [-0.48111294 -0.90454745  0.98255422 -0.72900688]
 [-0.22448915  0.09688036  0.92180913  0.80054824]
 [ 0.07416085 -0.023427    1.75501283  1.60189313]
 [ 1.14122768 -0.31066618  1.06688607  0.35661904]]


array([[-0.52837376, -0.17379724, -1.63033151, -0.37300834],
       [-0.6720027 , -0.76328834, -0.40674631,  1.25120439],
       [-0.72900688,  0.98255422, -0.90454745, -0.48111294],
       [ 0.80054824,  0.92180913,  0.09688036, -0.22448915],
       [ 1.60189313,  1.75501283, -0.023427  ,  0.07416085],
       [ 0.35661904,  1.06688607, -0.31066618,  1.14122768]])

# Fancy Slicing

In [18]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
#arr[slide, row, col]

In [24]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
print(a[[-1,-2,0],:,:])
print(a[[-1,-2,0]])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [23]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
print()
#print(a[:,[1,2], :])
print(a[:,1:, :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[[ 3  4  5]
  [ 6  7  8]]

 [[12 13 14]
  [15 16 17]]

 [[21 22 23]
  [24 25 26]]]


In [29]:
l = [1,29,8,2,9,3,2,1]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [27]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)
a[1] = 5
a

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 5,  5,  5],
        [ 5,  5,  5],
        [ 5,  5,  5]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
a = np.arange(3*3).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
#a[1:,1:]
a[1:3,1:3]
#a[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [52]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(len(a)):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [53]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i in range(a.shape[0]):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [57]:
a = np.arange(8*4).reshape((8,4))
print(a)
for i, _ in enumerate(a):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [56]:
list(enumerate([8,9,10]))

[(0, 8), (1, 9), (2, 10)]

In [60]:
a

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [61]:
print(a)
a[[5,4,3]]

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


array([[5, 5, 5, 5],
       [4, 4, 4, 4],
       [3, 3, 3, 3]])

In [68]:
a = np.arange(8*4).reshape((8,4))
print(a)
a[[5,4,3]][:,[3,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[23, 21],
       [19, 17],
       [15, 13]])

In [69]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

# Transposing Arrays and Swapping Axes

In [74]:
a = np.arange(4*3).reshape((4,3))
print(a)
print(a.T)
print(a.transpose())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [77]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a * b)


[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 3  8]
 [15 24]]


In [78]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a @ b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [79]:
a = np.array([[1,2],
            [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

print(a.dot(b))

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[13 16]
 [29 36]]


In [80]:
a

array([[1, 2],
       [3, 4]])

In [81]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [82]:
a @ a.T

array([[ 5, 11],
       [11, 25]])

In [83]:
a = np.arange(27).reshape((3,3,3))
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [84]:
a.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [85]:
print(a)
print(a.transpose((2,1,0)))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  9 18]
  [ 3 12 21]
  [ 6 15 24]]

 [[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]]


In [95]:
a = np.arange(12).reshape(4,3)
print(a)
print(a.swapaxes(1,0))
#print(a.reshape((a.shape[1], a.shape[0])))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [89]:
a.ndim

2

In [90]:
a.shape

(4, 3)

# 4.2 Universal Functions: Fast Element-Wise Array Functions

In [96]:
l = np.array([-1,3,-5,8,0])
np.abs(l)


array([1, 3, 5, 8, 0])

In [97]:
l = np.array([-1,3,-5,8,0])
np.fabs(l)

array([1., 3., 5., 8., 0.])

In [98]:
np.sqrt([36,25,9])

array([6., 5., 3.])

In [99]:
np.square([2,3,4])

array([ 4,  9, 16])

In [101]:
np.exp([2,3,5])

array([  7.3890561 ,  20.08553692, 148.4131591 ])

In [102]:
np.exp??

In [103]:
np.ceil([2.2, 3.1, 2.6])

array([3., 4., 3.])

In [104]:
np.floor([2.2, 3.1, 2.6])

array([2., 3., 2.])

In [114]:
a = np.array([2.2, 3.1, 2.6])
print(a)
print()
f, w = np.modf(a)
print(w,f, sep="\n\n")

[2.2 3.1 2.6]

[2. 3. 2.]

[0.2 0.1 0.6]


In [110]:
for i in [2.2, 3.1, 2.6]:
    i= str(i).split(".")
    print(i[0], i[1])

2 2
3 1
2 6


In [115]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.maximum(a,b))

[ 2  4 45]


In [116]:
a = np.array([1,3,45])
b = np.array([2,4,3])

np.fmax(a,b)

array([ 2,  4, 45])

In [119]:
a = np.arange(6*2).reshape((6,2))
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

# Expressing Conditional Logic as Array Operations

In [121]:
a = np.arange(3*3*3).reshape((3,3,3))
a %3 == 0

array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]])

np.where(condition, value_True, value_false)

In [122]:
np.where(a%3==0, "Yes","No")

array([[['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']],

       [['Yes', 'No', 'No'],
        ['Yes', 'No', 'No'],
        ['Yes', 'No', 'No']]], dtype='<U3')

In [123]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.where(a>b, a, b))

[ 2  4 45]
