In [3]:
%history

%history
sum([1,3,2])
%history


In [4]:
!touch fileName.py

In [ ]:
# %load fileName.py
print("Line1")
print("Line2")


In [6]:
%run fileName.py

Line1
Line2


In [7]:
%time sum([1,3,4])

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 14.8 µs


8

In [2]:
sum([1,3,2])

6

## Python Vs Numpy

In [13]:
%time l1 = list(range(1,3000000))

CPU times: user 79 ms, sys: 42.2 ms, total: 121 ms
Wall time: 127 ms


In [16]:
%time [x+5 for x in l1][:10]

CPU times: user 171 ms, sys: 98.1 ms, total: 269 ms
Wall time: 311 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [18]:
list(enumerate(['A','B',"C"]))

[(0, 'A'), (1, 'B'), (2, 'C')]

In [24]:
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]    

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [26]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print(a)
for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        

print("After Adding 5")
print(a)        

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [28]:
a = [1,2,3]
a + 5

TypeError: can only concatenate list (not "int") to list

#### numpy

In [10]:
import numpy as np

In [32]:
%time l2 = np.arange(1,3000000)

CPU times: user 2.2 ms, sys: 32.1 ms, total: 34.3 ms
Wall time: 44.7 ms


In [34]:
l1 = np.array([1])
print("Dimension:", l2.ndim)
print("Shape:", l2.shape)
print("Type:", l2.dtype)

Dimension: 1
Shape: (2999999,)
Type: int64


In [38]:
l1 = np.random.randn(2,2)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)
#l1[row,col]

[[1.47125843 2.49071193]
 [0.10666251 0.12005191]]
Dimension: 2
Shape: (2, 2)
Type: float64


In [40]:
l1 = np.random.randn(3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[[[-0.92403551 -0.19492633  0.07289328]
  [-0.80882656 -0.23839292 -0.01752686]
  [-0.33669569 -1.15779816  1.67631527]]

 [[ 0.38361036  0.65650523  0.50043071]
  [-0.88004281  0.31530807 -0.22970217]
  [-0.84590703  0.93786127  0.26952903]]

 [[ 1.14188197  0.55539167 -0.16307304]
  [ 0.51320962 -0.51096165 -2.67776784]
  [ 0.884293    0.6102596  -0.04489273]]]
Dimension: 3
Shape: (3, 3, 3)
Type: float64


In [45]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

l1[1,2,1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension: 3
Shape: (3, 3, 3)
Type: int64


16

<img src='https://www.pythoninformer.com/img/numpy/3d-array.png'>

In [ ]:
l1[i,j,k]

In [46]:
l1 = np.arange(27).reshape((3,3,3))
print(l1)

l1 = l1 + 5
l1

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28],
        [29, 30, 31]]])

# A Multidimensional Array Object

In [48]:
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int64


In [61]:
l1 = np.arange(1,26).reshape((5,5))
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Dimension: 2
Shape: (5, 5)
Type: int64


In [58]:
l1 = np.random.randn(3,3,3,3,3)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("itemsize", l1.itemsize)
print("Type:", l1.dtype)

[[[[[ 2.17997245e-01  1.17636034e-01 -1.88043211e-01]
    [-8.38270977e-01  5.73058264e-01  2.62179000e+00]
    [ 2.94423466e-01  1.26342188e+00 -1.11420967e+00]]

   [[ 1.41217879e-01  8.41753583e-01 -2.09826989e-01]
    [-6.47256815e-01  6.72733701e-01 -4.23388019e-01]
    [-3.57643586e-01  3.65479467e-01  1.82631594e-01]]

   [[-1.20782230e+00  5.24708364e-01 -2.28088869e-01]
    [-5.28284704e-01 -1.51464487e-01 -1.68459793e+00]
    [ 1.03134214e+00 -3.40389256e-01  1.15188231e+00]]]


  [[[-9.21864497e-01  1.76824878e+00  3.24093256e-01]
    [ 3.57961717e-01  1.07922793e+00 -4.53412373e-02]
    [-2.39591182e-01  2.94417738e-01  6.52140946e-01]]

   [[-1.38735478e+00  3.61815140e-01  8.14982045e-01]
    [ 3.73525987e-01  2.63650414e-02  5.71849998e-02]
    [ 1.04681139e+00 -3.77448023e-01 -4.05741767e-01]]

   [[ 5.97876454e-01 -1.20072196e+00 -1.00081816e+00]
    [ 4.90401155e-01  1.57397803e-02  6.69907507e-01]
    [ 9.68350211e-01  1.86170697e+00  4.38177477e-01]]]


  [[[ 6.5127

In [69]:
a = np.arange(1,28).reshape((3,3,3))
print(a ** .5)

[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]
  [2.64575131 2.82842712 3.        ]]

 [[3.16227766 3.31662479 3.46410162]
  [3.60555128 3.74165739 3.87298335]
  [4.         4.12310563 4.24264069]]

 [[4.35889894 4.47213595 4.58257569]
  [4.69041576 4.79583152 4.89897949]
  [5.         5.09901951 5.19615242]]]


# Creating ndarrays

#### np.array

In [70]:
# Deep Copy
l = [1,2,3]
print(type(l))

a = np.array(l)
b = np.array(a)

print(a is b)
type(a)

<class 'list'>
False


numpy.ndarray

### np.asarray

In [73]:
# 1 array->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #2
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#3

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [74]:
%history

%history
sum([1,3,2])
%history
!touch fileName.py
%load fileName.py
%run fileName.py
%time sum([1,3,4])
%time l1 = list(range(1,2000000))
%time l1 = list(range(1,3000000))
import numpy as np
%time l1 = np.arange(1,2000000)
%time l2 = np.arange(1,2000000)
%time l1 = list(range(1,3000000))
l1[:10]
%time [x+5 for x in l1]
%time [x+5 for x in l1][:10]
enumerate(['A','B',"C"])
list(enumerate(['A','B',"C"]))
for i, v for list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
%time
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]

%time for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    %time l1[i] = l1[i]+5
l1[:10]
for i, v in list(enumerate(l1)):
    l1[i] = l1[i]+5
l1[:10]
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 5")
print