In [3]:
%history

%history
print("Helloworld")
%history


In [2]:
print("Helloworld")

Helloworld


In [4]:
print("Line1")
print("Line2")

Line1
Line2


In [ ]:
# %load fileName.py
print("Line1")
print("Line2")


In [6]:
%run fileName.py

Line1
Line2


In [7]:
%time print("ada")

ada
CPU times: user 506 µs, sys: 136 µs, total: 642 µs
Wall time: 649 µs


# Python

In [14]:
%time l1 = list(range(1,3000000))
print(l1[:10])

CPU times: user 85.3 ms, sys: 52.8 ms, total: 138 ms
Wall time: 154 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
%time [x+5 for x in l1][:10]

CPU times: user 258 ms, sys: 71 ms, total: 329 ms
Wall time: 489 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [20]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [21]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [22]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [25]:
l1 = [1,2,4]
l1 + 5

TypeError: can only concatenate list (not "int") to list

# Numpy 

In [1]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [11]:
#import numpy as *
import numpy as np

In [12]:
l = [1,3,2]
print(sum(l))
print(np.sum(l))

6
6


In [24]:
l1 = np.arange(1,3000000)
%time l1 + 5

CPU times: user 10.3 ms, sys: 642 µs, total: 10.9 ms
Wall time: 12.7 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [26]:
l1 = np.arange(1,13)

print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

Diminsion: 1
Type: int64
Size: 12
Itemsize: 8
Shape: (12,)


# A Multidimensional Array Object

In [34]:
#l1 = np.arange(1,13).reshape((4,3))
#l1 = np.arange(1,13).reshape((3,4))
#l1 = np.arange(1,13).reshape((2,6))
#l1 = np.arange(1,13).reshape((6,2))
l1 = np.arange(1,13).reshape((12,1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Diminsion: 2
Type: int64
Size: 12
Itemsize: 8
Shape: (12, 1)


<img src="https://www.pythoninformer.com/img/numpy/3d-array-stack.png">
<img src="https://www.pythoninformer.com/img/numpy/3d-array.png">

In [36]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [40]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
#l1[1]
#l1[1,2]
l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [42]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [43]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[-1.64862618e-01 -1.06401826e+00 -9.38454295e-01]
  [-1.28984536e+00 -5.75264216e-01 -1.48039211e-01]
  [-1.45804769e-01 -1.36227695e+00  4.27366617e-01]]

 [[ 1.98609550e+00 -4.98817498e-02 -1.55501169e-03]
  [-2.86247610e-03 -1.19001345e+00 -5.44593586e-01]
  [-1.22419921e+00  3.45676982e-01  5.35868746e-01]]

 [[ 9.75875944e-01 -2.10176417e+00  9.16510518e-01]
  [ 2.94217262e-01  8.58220098e-02  2.53974536e+00]
  [-1.72470622e+00  9.32735433e-01 -6.26833771e-01]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [51]:
#l1 + 2
#l1 * 2
#l1 / 2
#l1 ** 2
#l1 ** 0.5
#l1 % 2

array([[[-3.29725237e-01, -2.12803651e+00, -1.87690859e+00],
        [-2.57969072e+00, -1.15052843e+00, -2.96078422e-01],
        [-2.91609539e-01, -2.72455390e+00,  8.54733233e-01]],

       [[ 3.97219100e+00, -9.97634995e-02, -3.11002338e-03],
        [-5.72495220e-03, -2.38002689e+00, -1.08918717e+00],
        [-2.44839842e+00,  6.91353963e-01,  1.07173749e+00]],

       [[ 1.95175189e+00, -4.20352834e+00,  1.83302104e+00],
        [ 5.88434524e-01,  1.71644020e-01,  5.07949072e+00],
        [-3.44941244e+00,  1.86547087e+00, -1.25366754e+00]]])

# Creating ndarrays

##### np.array()

In [52]:
# Deep Copy(Always copy)
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #True

False
False


In [54]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [3]:
import numpy as np
a = np.array([1,2])
a.itemsize

8

# Class 2

In [1]:
import numpy as np

## Creating ndarrays

In [2]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])

In [4]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

# Chaining

In [7]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7    

In [9]:
C(B(A(1)))

19

In [10]:
A(B(C(1)))

19

In [ ]:
np.A().B().C()

In [ ]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [12]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [13]:
a = np.reshape(np.arange(1,28), (3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [18]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [23]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [26]:
a.shape

(9, 3)

In [21]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [31]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [35]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [37]:
b = np.full_like(a, 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [38]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [41]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [45]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [46]:
np.empty_like(a)

array([[4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528],
       [4612811918334230528, 4612811918334230528, 4612811918334230528]])

In [51]:
np.full_like(a, 1) * np.nan


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [53]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [55]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [58]:
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int64')

In [65]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int64')

In [59]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [61]:
a = np.array([1,3,4], dtype='i8')
a.dtype

dtype('int64')

In [63]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int64')

In [64]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

# Boolen Operation

In [66]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [68]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [ ]:
print(a)
a[a%3==0]

In [74]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [75]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [76]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [77]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])