In [1]:
import numpy as np

In [4]:
print(len(dir(np)))
dir(np)[-10:]

624


['version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

In [2]:
np.__version__

'1.18.2'

In [6]:
!pip install --upgrade numpy

     |████████████████████████████████| 20.2MB 388kB/s eta 0:00:01    |████████████▋                   | 7.9MB 305kB/s eta 0:00:41
ERROR: tensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow-gpu 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
  Found existing installation: numpy 1.17.4
    Uninstalling numpy-1.17.4:
      Successfully uninstalled numpy-1.17.4


# In NumPy dimensions are called axes

In [11]:
a = [[1, 2, 3],
    [4, 5, 6]]


<class 'list'>


In [6]:
a = [1,3,4]
a = np.array(a)
print(a)
print(a.dtype)

a = (1,3,4)
a = np.array(a)
print(a)
print(a.dtype)

a = {1,3,4}
a = np.array(a)
print(a)
print(type(a))

[1 3 4]
int64
[1 3 4]
int64
{1, 3, 4}
<class 'numpy.ndarray'>


In [12]:
import numpy as np

In [31]:
%time np.arange(2000000)

CPU times: user 3.54 ms, sys: 38 ms, total: 41.5 ms
Wall time: 509 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [35]:
#%time list(range(2000000))
%time list(range(2000000))[:10]

CPU times: user 56.7 ms, sys: 24.9 ms, total: 81.6 ms
Wall time: 81.6 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
%time my_arr * 2

CPU times: user 4.56 ms, sys: 62 µs, total: 4.62 ms
Wall time: 3.96 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [36]:
# Python List1

In [41]:
python_list = list(range(1,11))
l2 = []
for n in python_list:
    l2.append(n*2)
print(l2)   
%time

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 13.6 µs


In [52]:
%time list(range(1000))

CPU times: user 71 µs, sys: 15 µs, total: 86 µs
Wall time: 101 µs


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [7]:
%time np.arange(1000)[:10]

CPU times: user 15 µs, sys: 4 µs, total: 19 µs
Wall time: 22.2 µs


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr1 = list(range(1,11))
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [74]:
arr2 = np.array(arr1)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [81]:
a = [1, 2]
np.asarray(a)

array([1, 2])

In [85]:
a = np.array([1, 2])
np.asarray(a) is a

True

In [86]:
a

array([1, 2])

In [87]:
np.asarray??

In [89]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [91]:
np.full((3,3), fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [93]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
a = [1,2,3]
a = np.array(a)
b = np.array(a)
a is b

False

In [12]:
a = [1,2,3]
a = np.asarray(a)
b = np.asarray(a)
a is b

True

In [22]:
a = np.array([1,2,3], dtype='i1')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u1')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i2')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u2')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i4')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u4')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i8')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u8')
print(a, a.dtype)

[1 2 3] int8
[1 2 3] uint8
[1 2 3] int16
[1 2 3] uint16
[1 2 3] int32
[1 2 3] uint32
[1 2 3] int64
[1 2 3] uint64


<img src="https://miro.medium.com/max/878/1*mKoaKq1I7LGg82DhrDmgPA.png">

In [24]:
a = np.arange(27).reshape((3,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
a = np.arange(1,11)
print(a)
b = a.reshape((2,5))
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
a = np.arange(1,11)
print(a)
a.resize((2,5)) # Inplace
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Apply Addition operation on matrix with core python

In [43]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 2")
print(a)

for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c] + 2

print("After Adding 2")        
print(a)        

Before Adding 2
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 2
[[3, 4, 5], [6, 7, 8], [9, 10, 11]]


#### Apply Addition operation on matrix with Numpy

In [47]:
a = np.arange(9).reshape((3,3))
print("Before Adding 2")
print(a)

a = a + 2 

print("After Adding 2")        
print(a)   

Before Adding 2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After Adding 2
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# Class2

### Basics Slice 

In [2]:
import numpy as np

In [8]:
a = np.random.randn??

In [ ]:
a = np.random.randn

In [58]:
a = np.arange(1,10).reshape((3,3))
b = a[:].copy()

print(a[0])
print(b[0])
print()
b += 2
print(a[0])
print(b[0])

[1 2 3]
[1 2 3]

[1 2 3]
[3 4 5]


In [26]:
a[1:][1:][:]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [33]:
b = a[1:,1:,:]
b = b+10
b

array([[[23, 24, 25],
        [26, 27, 28]],

       [[32, 33, 34],
        [35, 36, 37]]])

In [39]:
b= a[1:,:,:]
b = b+10

In [40]:
b

array([[[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[29, 30, 31],
        [32, 33, 34],
        [35, 36, 37]]])

In [41]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.17362033  0.97449109  2.30172516 -1.53932409]
 [ 0.25620451 -0.29627393  0.07696563 -0.46093535]
 [-0.18145339 -1.66871887  0.07565216  0.27380268]
 [ 0.37466548  0.56867728 -0.46181768  0.55561886]
 [-0.26410576  0.74756366  0.64274921  1.22893656]
 [-0.44515765 -1.82856649  1.12310794  0.4089585 ]
 [ 0.98976635  0.05942119 -0.44878935 -1.48446753]]


In [68]:
data[[0,3]]

array([[-1.17362033,  0.97449109,  2.30172516, -1.53932409],
       [ 0.37466548,  0.56867728, -0.46181768,  0.55561886]])

In [69]:
data[names=='Bob']

array([[-1.17362033,  0.97449109,  2.30172516, -1.53932409],
       [ 0.37466548,  0.56867728, -0.46181768,  0.55561886]])

In [80]:
a = np.arange(1,29).reshape((2,14))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [87]:
a.transpose((0,1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [103]:
a = np.arange(1,21).reshape((2,5,2))
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [106]:
a.transpose((1,2,0))

array([[[ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14]],

       [[ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18]],

       [[ 9, 19],
        [10, 20]]])

In [105]:
a.transpose()

array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [115]:
print(a.shape)
a.swapaxes(2,0)

(2, 5, 2)


array([[[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]],

       [[ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18],
        [10, 20]]])

In [111]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [122]:
np.fabs??

In [119]:
np.abs(np.random.rand(8))

array([0.51402668, 0.92660415, 0.26658424, 0.81345523, 0.31741779,
       0.45206691, 0.77867779, 0.13712367])

In [126]:
np.floor(10.7)

10.0

In [129]:
np.isinf(np.inf)

True

In [131]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.add(a,2)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [134]:
a//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [135]:
a.copysign??

Object `a.copysign` not found.


In [136]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

In [140]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [141]:
b = a * 2
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [144]:
c = a % 2 == 0
c

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [145]:
np.where(c,a, b)

array([ 2,  2,  6,  4, 10,  6, 14,  8, 18, 10, 22, 12])

In [162]:
a = np.arange(12).reshape((3,4))

In [163]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.cumprod(a, axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

In [165]:
a.cumprod(axis=0)

array([[  0,   1,   2,   3],
       [  0,   5,  12,  21],
       [  0,  45, 120, 231]])

In [166]:
np.cumprod??

In [153]:
a = np.arange(1,12)
np.cumprod(a)

array([       1,        2,        6,       24,      120,      720,
           5040,    40320,   362880,  3628800, 39916800])

In [2]:
a = np.arange(1,5).reshape((2,2))
print(a)
print(a.T)

a.dot(a)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


array([[ 7, 10],
       [15, 22]])

In [8]:
np.fromfunction??

In [11]:
np.fromfunction(lambda x,y: x+y, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [17]:
a.flatten()

array([1, 2, 3, 4])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [19]:
a.ravel()

array([1, 2, 3, 4])

In [20]:
a

array([[1, 2],
       [3, 4]])

In [21]:
a.T

array([[1, 3],
       [2, 4]])

In [22]:
a

array([[1, 2],
       [3, 4]])

In [25]:
np.vstack((a,a))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [26]:
np.hstack((a,a))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [27]:
np.column_stack((a,a))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [28]:
np.row_stack((a,a))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [31]:
np._r[:5, 1,3]

AttributeError: module 'numpy' has no attribute '_r'

In [32]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [34]:
np.linalg.inv??

In [1]:
import numpy as np

In [2]:
a = np.arange(4*3).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
b = np.arange(3*2).reshape(3,2)
c = b+1
print(b)
print()
print(c)

[[0 1]
 [2 3]
 [4 5]]

[[1 2]
 [3 4]
 [5 6]]


In [12]:
b = np.arange(3*2).reshape(3,2)
c = b+1
print(b)
print()
print(c)

np.stack((b,c), axis=1)

[[0 1]
 [2 3]
 [4 5]]

[[1 2]
 [3 4]
 [5 6]]


array([[[0, 1],
        [1, 2]],

       [[2, 3],
        [3, 4]],

       [[4, 5],
        [5, 6]]])

In [13]:
b = np.arange(3*2).reshape(3,2)
c = b+1
print(b)
print()
print(c)
np.vstack((b,c))

[[0 1]
 [2 3]
 [4 5]]

[[1 2]
 [3 4]
 [5 6]]


array([[0, 1],
       [2, 3],
       [4, 5],
       [1, 2],
       [3, 4],
       [5, 6]])

In [15]:
np.concatenate((b,c), axis=1)

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [19]:
np.block([b,c])

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [20]:
np.column_stack((b,c))

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6]])

In [23]:
np.stack((b,c), axis=0)

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [29]:
b = np.arange(2*3*3).reshape(2,3,3)
c = b+1
print(b,c, sep="\n\n")
np.dstack((b,c))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[[ 0,  1,  2,  1,  2,  3],
        [ 3,  4,  5,  4,  5,  6],
        [ 6,  7,  8,  7,  8,  9]],

       [[ 9, 10, 11, 10, 11, 12],
        [12, 13, 14, 13, 14, 15],
        [15, 16, 17, 16, 17, 18]]])

In [31]:
b = np.arange(2*3*3).reshape(2,3,3)
c = b+1
print(b,c, sep="\n\n")
np.dstack((b,c))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[[ 0,  1,  2,  1,  2,  3],
        [ 3,  4,  5,  4,  5,  6],
        [ 6,  7,  8,  7,  8,  9]],

       [[ 9, 10, 11, 10, 11, 12],
        [12, 13, 14, 13, 14, 15],
        [15, 16, 17, 16, 17, 18]]])

In [35]:
print(a)
np.split(a, 2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [37]:
print(a)
np.split(a, 3, axis=1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [41]:
print(a)
np.hsplit(a,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [42]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6],
        [9]]), array([[ 1],
        [ 4],
        [ 7],
        [10]]), array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [50]:
print(a)
np.split(a,4, axis=0)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [52]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
np.dsplit(a,3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [57]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
b = np.array([1,200,4,7,10,13,16,400])
print(b)

print(np.in1d(b,a))

print(np.intersect1d(b,a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[  1 200   4   7  10  13  16 400]
[ True False  True  True  True  True  True False]
[ 1  4  7 10 13 16]


In [58]:

print(np.union1d(b,a))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26 200 400]


In [59]:
print(a)
print(np.setdiff1d(b,a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[200 400]


In [60]:
print(a)
print(np.setxor1d(b,a))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[  0   2   3   5   6   8   9  11  12  14  15  17  18  19  20  21  22  23
  24  25  26 200 400]


In [61]:
np.save('abc',a)

In [62]:
np.load('abc.npy')

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
a = np.array([[1,2,3],
             [4,5,6]])
b = a+1
print(a,b, sep='\n\n')

print(a*b)

[[1 2 3]
 [4 5 6]]

[[2 3 4]
 [5 6 7]]
[[ 2  6 12]
 [20 30 42]]


In [76]:
a = np.array([[1,2,3],
             [4,5,6]])
b = a+1


print(a ,sep='\n\n')
print()
print(b.T)
print()
print(a @ b.T)

[[1 2 3]
 [4 5 6]]

[[2 5]
 [3 6]
 [4 7]]

[[20 38]
 [47 92]]


In [78]:
a.dot(b.T)

array([[20, 38],
       [47, 92]])

In [79]:
np.linalg.inv??

In [81]:
a = np.arange(3*3).reshape((3,3))
print(a)
np.diag(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [82]:
a = np.arange(3*3).reshape((3,3))
print(a)
np.trace(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


12

In [84]:
a = np.arange(3*3).reshape((3,3))
print(a)
np.linalg.det(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


0.0

In [85]:
a = np.arange(3*3).reshape((3,3))
print(a)
np.linalg.eig(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(array([ 1.33484692e+01, -1.34846923e+00, -2.48477279e-16]),
 array([[ 0.16476382,  0.79969966,  0.40824829],
        [ 0.50577448,  0.10420579, -0.81649658],
        [ 0.84678513, -0.59128809,  0.40824829]]))

In [86]:
np.linalg.eig??

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10, size=10)
b = np.random.randint(1,5, size=5)
print(a, b , sep='\n\n')

[9 3 3 8 6 4 8 6 7 3]

[4 3 2 4 1]


In [3]:
np.intersect1d(a,b)

array([3, 4])

In [4]:
np.union1d(a,b)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [6]:
print(b, a, sep='\n\n')
np.in1d(b,a)

[4 3 2 4 1]

[9 3 3 8 6 4 8 6 7 3]


array([ True,  True, False,  True, False])

In [7]:
print(b, a, sep='\n\n')
np.setdiff1d(b,a)

[4 3 2 4 1]

[9 3 3 8 6 4 8 6 7 3]


array([1, 2])

In [8]:
print(b, a, sep='\n\n')
np.setxor1d(b,a)

[4 3 2 4 1]

[9 3 3 8 6 4 8 6 7 3]


array([1, 2, 6, 7, 8, 9])

In [9]:
import matplotlib.pyplot as plt
a = np.permutation??

Object `np.permutation` not found.


In [ ]:
###### from scipy import stats
a = np.random.rand(100)
a.sort()
print(np.mean(a))
print(np.median(a))
print(stats.mode(a))
plt.plot(a)
plt.show()

In [30]:
a = np.random.randn(4,4)
a

array([[-1.46480904,  0.56706655,  0.48592192,  1.17912734],
       [-0.19093761, -0.5849651 , -2.05835744, -0.10840999],
       [-0.31469328,  1.9281949 ,  0.62070067,  0.73072014],
       [-0.71257076, -0.14490393, -2.39313188, -0.80357378]])

In [31]:
np.diag(a)

array([-1.46480904, -0.5849651 ,  0.62070067, -0.80357378])

In [32]:
np.trace(a)

-2.2326472494348932

In [36]:
np.linalg.eig(a)

(array([-0.24802768+2.35930334j, -0.24802768-2.35930334j,
        -0.86829595+0.54132774j, -0.86829595-0.54132774j]),
 array([[ 0.06165339-0.34696599j,  0.06165339+0.34696599j,
          0.76661549+0.j        ,  0.76661549-0.j        ],
        [ 0.46854521-0.06440288j,  0.46854521+0.06440288j,
          0.08716736-0.15322361j,  0.08716736+0.15322361j],
        [-0.18837133-0.49432216j, -0.18837133+0.49432216j,
         -0.12023864-0.06790657j, -0.12023864+0.06790657j],
        [ 0.61015815+0.j        ,  0.61015815-0.j        ,
          0.39545608+0.4536198j ,  0.39545608-0.4536198j ]]))

In [37]:
np.linalg.svd(a)

(array([[-0.28056182, -0.65812017,  0.6949288 , -0.07236618],
        [ 0.55981736, -0.23541585,  0.08532065,  0.78987612],
        [-0.41687828, -0.5653826 , -0.68284004,  0.20071   ],
        [ 0.65886424, -0.43794947, -0.20862367, -0.57495595]]),
 array([3.63098965, 2.28949133, 1.27410859, 0.55629637]),
 array([[-0.00942423, -0.38167705, -0.86041033, -0.33753203],
        [ 0.65471408, -0.55129937,  0.37646459, -0.35453194],
        [-0.52639517, -0.73954216,  0.18639339,  0.37582313],
        [ 0.54237329, -0.05889851, -0.28848912,  0.78685209]]))

In [38]:
np.any([True,False,True])

True

In [39]:
np.all([True,False,True])

False

In [41]:
import pandas_datareader.data as web
import datetime
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2013, 1, 27)
f = web.DataReader('F', 'google', start, end)
f.ix['2010-01-04']

ModuleNotFoundError: No module named 'pandas_datareader'

In [44]:
import pandas as pd
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
print(obj)
obj.rank()


0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64


0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [55]:
a = np.arange(1,6)
b = np.arange(6,11)
print(a,b, sep='\n\n')

[1 2 3 4 5]

[ 6  7  8  9 10]


In [56]:
np.stack((a,b), axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
np.stack((a,b), axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [61]:
np.block([[a],[b]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [62]:
np.block([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [65]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [66]:
a = np.arange(1,2*2*2+1).reshape((2,2,2))
b = a*2
print(a,b, sep="\n\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [67]:
np.dstack((a,b))

array([[[ 1,  2,  2,  4],
        [ 3,  4,  6,  8]],

       [[ 5,  6, 10, 12],
        [ 7,  8, 14, 16]]])

In [71]:
a = np.arange(1,6*6+1).reshape((6,6))
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [73]:
np.split(a, 3, axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [74]:
np.split(a, 3, axis=1)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]), array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]), array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [75]:
a = np.arange(1,2*2*2+1).reshape((2,2,2))
b = a*2
print(a,b, sep="\n\n")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

[[[ 2  4]
  [ 6  8]]

 [[10 12]
  [14 16]]]


In [80]:
np.dsplit(a,2)

[array([[[1],
         [3]],
 
        [[5],
         [7]]]), array([[[2],
         [4]],
 
        [[6],
         [8]]])]

In [81]:
np.dsplit??

In [85]:
a = np.arange(1,6*6+1).reshape((6,6))
print(a)
np.hsplit(a,6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1],
        [ 7],
        [13],
        [19],
        [25],
        [31]]), array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]), array([[ 3],
        [ 9],
        [15],
        [21],
        [27],
        [33]]), array([[ 4],
        [10],
        [16],
        [22],
        [28],
        [34]]), array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]), array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [86]:
a = np.arange(1,6*6+1).reshape((6,6))
print(a)
np.vsplit(a,6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36]])]

In [90]:
b = a*2
print(a,b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]] [[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


In [97]:
np.stack((a,b), axis=2)

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6],
        [ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18],
        [10, 20],
        [11, 22],
        [12, 24]],

       [[13, 26],
        [14, 28],
        [15, 30],
        [16, 32],
        [17, 34],
        [18, 36]],

       [[19, 38],
        [20, 40],
        [21, 42],
        [22, 44],
        [23, 46],
        [24, 48]],

       [[25, 50],
        [26, 52],
        [27, 54],
        [28, 56],
        [29, 58],
        [30, 60]],

       [[31, 62],
        [32, 64],
        [33, 66],
        [34, 68],
        [35, 70],
        [36, 72]]])

In [99]:
df1 = pd.read_html("https://www.w3schools.com/html/html_tables.asp")
df1[0]

0                 1        2
0                       Company           Contact  Country
1           Alfreds Futterkiste      Maria Anders  Germany
2    Centro comercial Moctezuma   Francisco Chang   Mexico
3                  Ernst Handel     Roland Mendel  Austria
4                Island Trading     Helen Bennett       UK
5  Laughing Bacchus Winecellars   Yoshi Tannamuri   Canada
6  Magazzini Alimentari Riuniti  Giovanni Rovelli    Italy

In [120]:
# %load "/home/muhammadqasim/anaconda3/lib/python3.7/site-packages/tabula/__init__.py"
!pip install tabula-py

     |████████████████████████████████| 10.4MB 192kB/s eta 0:00:01
     |████████████████████████████████| 10.0MB 136kB/s eta 0:00:01    |████████████████████▋           | 6.5MB 209kB/s eta 0:00:18     |█████████████████████████▌      | 8.0MB 264kB/s eta 0:00:08
  Found existing installation: pandas 0.23.4
    Uninstalling pandas-0.23.4:
      Successfully uninstalled pandas-0.23.4


In [161]:
import tabula
taubla.read_pdf??

Object `taubla.read_pdf` not found.


In [116]:
tabula

<module 'tabula' from '/home/muhammadqasim/anaconda3/lib/python3.7/site-packages/tabula/__init__.py'>

In [119]:
df1 = pd.read_json("https://api.github.com/users/hadley/orgs")
df1.head(2)

avatar_url description  \
0  https://avatars1.githubusercontent.com/u/42363...               
1  https://avatars1.githubusercontent.com/u/51356...        None   

                                   events_url  \
0    https://api.github.com/orgs/ggobi/events   
1  https://api.github.com/orgs/rstudio/events   

                                   hooks_url      id  \
0    https://api.github.com/orgs/ggobi/hooks  423638   
1  https://api.github.com/orgs/rstudio/hooks  513560   

                                   issues_url    login  \
0    https://api.github.com/orgs/ggobi/issues    ggobi   
1  https://api.github.com/orgs/rstudio/issues  rstudio   

                                         members_url  \
0  https://api.github.com/orgs/ggobi/members{/mem...   
1  https://api.github.com/orgs/rstudio/members{/m...   

                            node_id  \
0  MDEyOk9yZ2FuaXphdGlvbjQyMzYzOA==   
1  MDEyOk9yZ2FuaXphdGlvbjUxMzU2MA==   

                                  public_members_url  \
0  https://api.github.com/orgs/ggobi/public_membe...   
1  https://api.github.com/orgs/rstudio/public_mem...   

                                   repos_url  \
0    https://api.github.com/orgs/ggobi/repos   
1  https://api.github.com/orgs/rstudio/repos   

                                   url  
0    https://api.github.com/orgs/ggobi  
1  https://api.github.com/orgs/rstudio

In [127]:
pd.read_excel??

In [4]:
df = pd.read_excel("abc.xlsx")
df

ID  Name  Course  Timing
0   65  92.5    27.5  756.25
1  120  92.5   -27.5  756.25
2   90  92.5     2.5    6.25
3   95  92.5    -2.5    6.25

In [130]:
pd.read_feather??

In [139]:
df1.to_feather("ab.ft")

In [142]:
df1.to_pickle('ab.pkl')

In [154]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]},
                  index=['a', 'b', 'c'])
df.to_hdf('data.h5', key='df', mode='w')

In [158]:
df.to_dict()

{'A': {'a': 1, 'b': 2, 'c': 3}, 'B': {'a': 4, 'b': 5, 'c': 6}}

In [159]:
df.to_dense()

A  B
a  1  4
b  2  5
c  3  6

In [160]:
pd.rea

In [174]:
type(pd.date_range('2020-01-01','2020-01-31',freq='5H'))

pandas.core.indexes.datetimes.DatetimeIndex

In [172]:
pd.date_range??

In [191]:
df1 = pd.DataFrame(np.random.randint(1,10,size=(6,4)))
df1.columns = ["A","B","C","D"]
df1

A  B  C  D
0  7  7  1  5
1  8  3  1  8
2  9  8  8  2
3  4  5  7  5
4  2  1  3  4
5  2  1  4  8

In [192]:
!pip install --upgrade pandas

Requirement already up-to-date: pandas in /home/muhammadqasim/anaconda3/lib/python3.7/site-packages (1.0.3)


In [193]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [1]:
def f1(a,b):
    return a+b

df1['total'] = df1.sum(axis=1)
df1

NameError: name 'df1' is not defined

In [2]:
import pandas as pd

In [5]:
df.head()

ID  Name  Course  Timing
0   65  92.5    27.5  756.25
1  120  92.5   -27.5  756.25
2   90  92.5     2.5    6.25
3   95  92.5    -2.5    6.25

In [9]:
def f1(a,b):
    return a + b
df['total'] = df[["Name","Timing"]].apply(lambda x:f1(*x), axis=1)

In [10]:
df

ID  Name  Course  Timing   total
0   65  92.5    27.5  756.25  848.75
1  120  92.5   -27.5  756.25  848.75
2   90  92.5     2.5    6.25   98.75
3   95  92.5    -2.5    6.25   98.75