In [1]:
import numpy as np

In [4]:
print(len(dir(np)))
dir(np)[-10:]

624


['version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

In [2]:
np.__version__

'1.18.2'

In [6]:
!pip install --upgrade numpy

     |████████████████████████████████| 20.2MB 388kB/s eta 0:00:01    |████████████▋                   | 7.9MB 305kB/s eta 0:00:41
ERROR: tensorflow-gpu 1.13.1 has requirement tensorboard<1.14.0,>=1.13.0, but you'll have tensorboard 2.0.0 which is incompatible.
ERROR: tensorflow-gpu 1.13.1 has requirement tensorflow-estimator<1.14.0rc0,>=1.13.0, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
  Found existing installation: numpy 1.17.4
    Uninstalling numpy-1.17.4:
      Successfully uninstalled numpy-1.17.4


# In NumPy dimensions are called axes

In [11]:
a = [[1, 2, 3],
    [4, 5, 6]]


<class 'list'>


In [6]:
a = [1,3,4]
a = np.array(a)
print(a)
print(a.dtype)

a = (1,3,4)
a = np.array(a)
print(a)
print(a.dtype)

a = {1,3,4}
a = np.array(a)
print(a)
print(type(a))

[1 3 4]
int64
[1 3 4]
int64
{1, 3, 4}
<class 'numpy.ndarray'>


In [12]:
import numpy as np

In [31]:
%time np.arange(2000000)

CPU times: user 3.54 ms, sys: 38 ms, total: 41.5 ms
Wall time: 509 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [35]:
#%time list(range(2000000))
%time list(range(2000000))[:10]

CPU times: user 56.7 ms, sys: 24.9 ms, total: 81.6 ms
Wall time: 81.6 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
%time my_arr * 2

CPU times: user 4.56 ms, sys: 62 µs, total: 4.62 ms
Wall time: 3.96 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [36]:
# Python List1

In [41]:
python_list = list(range(1,11))
l2 = []
for n in python_list:
    l2.append(n*2)
print(l2)   
%time

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
CPU times: user 6 µs, sys: 1 µs, total: 7 µs
Wall time: 13.6 µs


In [52]:
%time list(range(1000))

CPU times: user 71 µs, sys: 15 µs, total: 86 µs
Wall time: 101 µs


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [7]:
%time np.arange(1000)[:10]

CPU times: user 15 µs, sys: 4 µs, total: 19 µs
Wall time: 22.2 µs


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr1 = list(range(1,11))
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [74]:
arr2 = np.array(arr1)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [81]:
a = [1, 2]
np.asarray(a)

array([1, 2])

In [85]:
a = np.array([1, 2])
np.asarray(a) is a

True

In [86]:
a

array([1, 2])

In [87]:
np.asarray??

In [89]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [91]:
np.full((3,3), fill_value=2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [93]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
a = [1,2,3]
a = np.array(a)
b = np.array(a)
a is b

False

In [12]:
a = [1,2,3]
a = np.asarray(a)
b = np.asarray(a)
a is b

True

In [22]:
a = np.array([1,2,3], dtype='i1')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u1')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i2')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u2')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i4')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u4')
print(a, a.dtype)

a = np.array([1,2,3], dtype='i8')
print(a, a.dtype)
a = np.array([1,2,3], dtype='u8')
print(a, a.dtype)

[1 2 3] int8
[1 2 3] uint8
[1 2 3] int16
[1 2 3] uint16
[1 2 3] int32
[1 2 3] uint32
[1 2 3] int64
[1 2 3] uint64


<img src="https://miro.medium.com/max/878/1*mKoaKq1I7LGg82DhrDmgPA.png">

In [24]:
a = np.arange(27).reshape((3,3,3))
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
a = np.arange(1,11)
print(a)
b = a.reshape((2,5))
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
a = np.arange(1,11)
print(a)
a.resize((2,5)) # Inplace
print(b)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### Apply Addition operation on matrix with core python

In [43]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]

print("Before Adding 2")
print(a)

for r, rd in list(enumerate(a)):
    for c, cd in list(enumerate(rd)):
        a[r][c] = a[r][c] + 2

print("After Adding 2")        
print(a)        

Before Adding 2
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 2
[[3, 4, 5], [6, 7, 8], [9, 10, 11]]


#### Apply Addition operation on matrix with Numpy

In [47]:
a = np.arange(9).reshape((3,3))
print("Before Adding 2")
print(a)

a = a + 2 

print("After Adding 2")        
print(a)   

Before Adding 2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After Adding 2
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
