In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("./weight-height.csv",)
df.dtypes

Gender     object
Height    float64
Weight    float64
dtype: object

In [3]:
df.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [2]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [5]:
abc = {"Male":1, "Female":2}

df['G']=df.Gender.map(abc)
df.head()

Gender     Height      Weight  G
0   Male  73.847017  241.893563  1
1   Male  68.781904  162.310473  1
2   Male  74.110105  212.740856  1
3   Male  71.730978  220.042470  1
4   Male  69.881796  206.349801  1

In [7]:
df.loc[0:4, "Gender":"Weight"]

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [10]:
df.iloc[[0,2,0,4,3],[2,0,1]]

Weight Gender     Height
0  241.893563   Male  73.847017
2  212.740856   Male  74.110105
0  241.893563   Male  73.847017
4  206.349801   Male  69.881796
3  220.042470   Male  71.730978

In [ ]:
df.to_csv("")

In [9]:
df1 = pd.DataFrame(data=[[5,7,9],
                         [8,9,10]])
df1

0  1   2
0  5  7   9
1  8  9  10

In [1]:
import numpy as np

In [15]:
def a(x,y):
    return x,y

np.fromfunction(a, (3,4))

(array([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.]]), array([[0., 1., 2., 3.],
        [0., 1., 2., 3.],
        [0., 1., 2., 3.]]))

In [4]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,2.7,3)
print(a)
print(b)
print(b.dtype.name)

[1 1 1]
[0.   1.35 2.7 ]
float64


In [5]:
def func(x):
    return x+2

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(func, 0, b)


array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
np.apply_along_axis(func, 1, b)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.argmax(b)

8

In [9]:
np.argsort([1,7,7,3])

array([0, 3, 1, 2])

In [10]:
np.ceil([1.2,3.7,7.2])

array([2., 4., 8.])

In [11]:

a=np.array([1,2,3])
b=np.array([3,4,5])

np.cov(a,b)

array([[1., 1.],
       [1., 1.]])

In [12]:
np.cov??

In [13]:

np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:

a = np.floor(10*np.random.random((2,2)))
a

array([[9., 7.],
       [1., 3.]])

In [17]:

b = np.floor(10*np.random.random((2,2)))
b

array([[9., 7.],
       [5., 4.]])

In [18]:
np.vstack((a,b))

array([[9., 7.],
       [1., 3.],
       [9., 7.],
       [5., 4.]])

In [19]:
np.hstack((a,b))

array([[9., 7., 9., 7.],
       [1., 3., 5., 4.]])

In [20]:
from numpy import newaxis
np.column_stack((a,b))  

array([[9., 7., 9., 7.],
       [1., 3., 5., 4.]])

In [21]:
print(a)
a[:,newaxis]  

[[9. 7.]
 [1. 3.]]


array([[[9., 7.]],

       [[1., 3.]]])

In [22]:
a = np.floor(10*np.random.random((2,12)))
a

array([[4., 2., 2., 4., 2., 5., 8., 5., 3., 3., 1., 0.],
       [3., 4., 3., 5., 4., 5., 3., 1., 7., 4., 4., 2.]])

In [25]:

np.hsplit(a,6)   # Split a into 3

[array([[4., 2.],
        [3., 4.]]), array([[2., 4.],
        [3., 5.]]), array([[2., 5.],
        [4., 5.]]), array([[8., 5.],
        [3., 1.]]), array([[3., 3.],
        [7., 4.]]), array([[1., 0.],
        [4., 2.]])]